<a href="https://colab.research.google.com/github/Noorudinz/DataScience/blob/Vector_Operation/Vector_operation2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

In [4]:
a = np.array([2, 3])

b = np.array([4, 4])

a_dot_b = np.dot(a, b)

print(a_dot_b)

20


Write a NumPy program to create a vector with values ​​from 0 to 12 and change the sign of the numbers in the range from 6 to 10.

In [6]:
x = np.arange(12)
print("Original vector:")
print(x)
print("After changing the sign of the numbers in the range from 6 to 10:")
x[(x >= 6) & (x <= 10)] *= -1
print(x)

Original vector:
[ 0  1  2  3  4  5  6  7  8  9 10 11]
After changing the sign of the numbers in the range from 6 to 10:
[  0   1   2   3   4   5  -6  -7  -8  -9 -10  11]


In [7]:
p = [[1, 0], [0, 1]]
q = [[1, 2], [3, 4]]
print("original matrix:")
print(p)
print(q)
result = np.outer(p, q)
print("Outer product of the said two vectors:")
print(result)

original matrix:
[[1, 0], [0, 1]]
[[1, 2], [3, 4]]
Outer product of the said two vectors:
[[1 2 3 4]
 [0 0 0 0]
 [0 0 0 0]
 [1 2 3 4]]


Program to multiply two matrices using nested loops

In [10]:
# Program to multiply two matrices using nested loops

# 3x3 matrix
X = [[12,7,3],
    [4 ,5,6],
    [7 ,8,9]]
# 3x4 matrix
Y = [[5,8,1,2],
    [6,7,3,0],
    [4,5,9,1]]
# result is 3x4
result = [[0,0,0,0],
         [0,0,0,0],
         [0,0,0,0]]

# iterate through rows of X
for i in range(len(X)):
   # iterate through columns of Y
   for j in range(len(Y[0])):
       # iterate through rows of Y
       for k in range(len(Y)):
           result[i][j] += X[i][k] * Y[k][j]

for r in result:
   print(r)


[114, 160, 60, 27]
[74, 97, 73, 14]
[119, 157, 112, 23]


In [11]:
 #3x3 matrix
X = [[12,7,3],
    [4 ,5,6],
    [7 ,8,9]]

# 3x4 matrix
Y = [[5,8,1,2],
    [6,7,3,0],
    [4,5,9,1]]

# result is 3x4
result = [[sum(a*b for a,b in zip(X_row,Y_col)) for Y_col in zip(*Y)] for X_row in X]

for r in result:
   print(r)

[114, 160, 60, 27]
[74, 97, 73, 14]
[119, 157, 112, 23]
